name: ⚙️ Task
description: Template to create a new task
labels: team-proto
body:
- type: textarea
  attributes:
    label: Task description
    placeholder: |
      Write here a meaningful description of the task
  validations:
    required: true
- type: textarea
  attributes:
    label: Definition of Done
    placeholder: |
      - [ ] task 1
      - [ ] task 2
      - [ ] ...
  validations:
    requiered: true
- type: textarea
  attributes:
    label: Required tickets to get material from Warehouse
    placeholder: |
      - icub-tech-iit/tickets#<ticket number>
      - ...
  validations:
    requiered: false