name: 💻✏️ Capital
description: Template to create a new task
labels: team-proto
body:
- type: input
  attributes:
    label: Project
    description: please select the project
    placeholder:  
  validations:
    required: true
- type: textarea
  id: activity
  attributes:
    label: Activity reason
    description: select the reason for the activity
    value: |
      - [ ] Update schematics
      - [ ] Update BOM
      - [ ] New robot schematics
      - [ ] Fix error
  validations:
    required: true    
- type: textarea
  id: informations
  attributes:
    label: Additonal informations
    descriptions: Write an activity description here
  validations:
    required: true