name: 💻✏️ Capital
description: Template to create a new task
labels: team-proto
body:
- type: dropdown
  id:   lala
  attributes:
    label:  Robot name 🤖
    description:  please select the name of the robot
    options:
      - "ergoCub 1.0 S/N:000"
      - "ergoCub 1.1.0 S/N:001"
      - "ergoCub 1.1.3 S/N:002"
        body:
        - type: dropdown
          id: robot
          attributes:
            label: iCub
            description: select version
            options:
              - "iCub 2.X"
              - "iCub 2"
              - "iCub 3"
              - "iCub Misc"
         validations:
          required: true     
  validations:
    required: true
body:
- type: textarea
  attributes:
    label: Task description
    placeholder: |
      Write here a meaningful description of the task
  validations:
    required: true
- type: textarea
  attributes:
    label: Definition of Done
    placeholder: |
      - [ ] task 1
      - [ ] task 2
      - [ ] ...
  validations:
    requiered: true