name: 💻✏️ Capital
description: Template to create a new task
labels: team-proto
body:
- type: dropdown
  id: robot
  attributes:
    label: Select project
    description: please select the project
    options:
      - ergoCub1.0 S/N:000
      - ergoCub1.1.0 S/N:001
      - ergoCub1.1.3 S/N:002
        body:
        - type: dropdown
          id: robot
          attributes:
            label: iCub
            description: select version
            options:
              - "iCub 2.X"
              - "iCub 2"
              - "iCub 3"
              - "iCub Misc"
          validations:
            required: true     
  validations:
    required: true
body:
- type: textarea
  attributes:
    label: Task description
    placeholder: |
      Write here a meaningful description of the task
  validations:
    required: true
- type: textarea
  attributes:
    label: Definition of Done
    placeholder: |
      - [ ] task 1
      - [ ] task 2
      - [ ] ...
  validations:
    requiered: true