name: 💻✏️ Capital
description: Template to create a new task
labels: team-proto
body:
- type: input
  attributes:
    label: Project
    description: please select the project
    placeholder:  
  validations:
    required: true
- type: textarea
  attributes:
    label: Activity reason
    placeholder: |
      - [ ] Fix error
      - [ ] Update schematics
      - [ ] Update BOM
      - [ ] New robot schematics
  validations:
    requiered: true
    - type: textarea
  attributes:
    label: Additonal information
    placeholder: |
      Write an activity description here
  validations:
    required: true